### ISSUE TITLE
Unable to run submit.py

### ISSUE THREAD

**Issue by yasuo19** [SenWu/emmental-tutorials#13]
Hi,

I am trying to run the submit.py script, but I'm unable to figure out list of parameters required. I have tried running "python submit.py --help" and got this:
Options:
  --CB TEXT                 Path to CB model
  --COPA TEXT               Path to COPA model
  --MultiRC TEXT            Path to MultiRC model
  --RTE TEXT                Path to RTE model
  --WiC TEXT                Path to WiC model
  --WSC TEXT                Path to WSC model
  --split [train|val|test]
  --batch_size INTEGER
  --data_dir TEXT           Path to data
  --submit_dir TEXT
  --help                    Show this message and exit.

Can someone give me an example of the syntax to be used to run it?
Thanks in advance :)

**Comment by SenWu** [comment]
Hi @yasuo19,

Here is an example to use submit.py
```
python submit.py first_submit \
    --CB CB.pth \
    --COPA COPA.pth \
    --MultiRC MultiRC.pth \
    --RTE RTE.pth \
    --WiC WiC.pth \
    --WSC WSC.pth
```
